# Generated by Django 4.1.7 on 2023-02-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added',
        ),
    ]
