# Generated by Django 4.1.7 on 2023-03-06 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Wet'), ('d', 'Dirty'), ('m', 'Mixed'), ('r', 'Dry')], max_length=1)),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapers', to='quickstart.baby')),
            ],
            options={
                'verbose_name_plural': 'Diapers',
            },
        ),
    ]
