# Generated by Django 4.1.7 on 2023-03-06 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_feeding', to='quickstart.baby'),
        ),
        migrations.CreateModel(
            name='Expressed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressed_feeding', to='quickstart.baby')),
            ],
            options={
                'verbose_name_plural': 'Expressed',
            },
        ),
    ]
